# currently docker daemon needs sudo
# as of version 18.06
sudo: required
services:
  - docker

# series of commands exc before tests run
before_install:
  - docker build -t bennettdixon16/react_travis_aws_basic -f Dockerfile.dev ./react_basic_mounted

# run the npm tests, using `-- --coverage` to auto exit for travis' sake
# because npm test suite default hangs and waits for user input
script:
  - docker run bennettdixon16/react_travis_aws_basic npm run test -- --coverage
